# Makefile autogenerated by Dyi on July 1, 2015
#
# Main target: all
# Sources:  command.ls  parse.ls 

.DEFAULT_GOAL := all


.PHONY: c-2m3s0w3l
c-2m3s0w3l: index.js


.PHONY: c-x9yxbm6c
c-x9yxbm6c: command.js parse.js


.PHONY: build
build: c-2m3s0w3l c-x9yxbm6c


.PHONY: test
test: k-yuk06upw


.PHONY: up
up: k-6f9wnp4r


.PHONY: major
major: k-n71j5lw4


.PHONY: minor
minor: k-ytyc10pr


.PHONY: patch
patch: k-6bxusk6e


.PHONY: docs
docs: k-auvltas2


.PHONY: prepare
prepare: .




.PHONY: all
all: 
	make build  


.PHONY: k-yuk06upw
k-yuk06upw:  
	./test/test.sh


.PHONY: k-6f9wnp4r
k-6f9wnp4r:  
	make clean && babel configure.js | node


.PHONY: k-n71j5lw4
k-n71j5lw4:  
	./node_modules/.bin/xyz -i major


.PHONY: k-ytyc10pr
k-ytyc10pr:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-6bxusk6e
k-6bxusk6e:  
	./node_modules/.bin/xyz -i patch


.PHONY: k-auvltas2
k-auvltas2:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: clean
clean:  
	rm -f index.js
	rm -f command.js
	rm -f parse.js


.PHONY: update
update: 
	make clean   
	node




index.js: command.ls 
	((echo '#!/usr/bin/env node') && lsc -c command.ls) > index.js && chmod +x index.js

command.js: command.ls 
	lsc -c command.ls

parse.js: parse.ls 
	lsc -c parse.ls

.: 
	mkdir -p .

