# Makefile autogenerated by Dyi on July 1, 2015
#
# Main target: all
# Sources:  command.ls  parse.ls 

.DEFAULT_GOAL := all


.PHONY: c-mgwcxskn
c-mgwcxskn: command.js parse.js


.PHONY: build
build: c-mgwcxskn


.PHONY: docs
docs: k-jw3ob4q8


.PHONY: test
test: k-nbg08kt4


.PHONY: up
up: k-vohpu2mu


.PHONY: major
major: k-bn824fn8 k-h15h5em4 k-lr0i2xjk


.PHONY: minor
minor: k-nec434gv k-4t9ta33r k-7iq31q1p


.PHONY: patch
patch: k-8hrjjnn6 k-03g2rgnk k-mqhhqvh6


.PHONY: prepare
prepare: .




.PHONY: k-dvq8tfcy
k-dvq8tfcy:  
	((echo '#!/usr/bin/env node') && cat command.js) > index.js


.PHONY: k-qbgwksi1
k-qbgwksi1:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-dvq8tfcy 
	make k-qbgwksi1  


.PHONY: k-jw3ob4q8
k-jw3ob4q8:  
	./node_modules/.bin/verb


.PHONY: k-nbg08kt4
k-nbg08kt4:  
	./test/test.sh


.PHONY: k-vohpu2mu
k-vohpu2mu:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-bn824fn8
k-bn824fn8:  
	make all


.PHONY: k-h15h5em4
k-h15h5em4:  
	make docs


.PHONY: k-lr0i2xjk
k-lr0i2xjk:  
	./node_modules/.bin/xyz -i major


.PHONY: k-nec434gv
k-nec434gv:  
	make all


.PHONY: k-4t9ta33r
k-4t9ta33r:  
	make docs


.PHONY: k-7iq31q1p
k-7iq31q1p:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-8hrjjnn6
k-8hrjjnn6:  
	make all


.PHONY: k-03g2rgnk
k-03g2rgnk:  
	make docs


.PHONY: k-mqhhqvh6
k-mqhhqvh6:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f command.js
	rm -f parse.js


.PHONY: update
update: 
	make clean   
	node




command.js: command.ls 
	lsc -c command.ls

parse.js: parse.ls 
	lsc -c parse.ls

.: 
	mkdir -p .

