// Generated by LiveScript 1.3.1
(function(){
  var _module;
  _module = function(){
    var y, moment, _, parse, iface;
    y = require('js-yaml');
    moment = require('moment');
    _ = require('underscore');
    _.str = require('underscore.string');
    _.mixin(_.str.exports());
    _.str.include('Underscore.string', 'string');
    parse = function(file){
      var yaml, content, isYaml, i$, ref$, len$, l, data, post;
      yaml = "";
      content = "";
      isYaml = false;
      for (i$ = 0, len$ = (ref$ = _.lines(file)).length; i$ < len$; ++i$) {
        l = ref$[i$];
        if (isYaml) {
          if (/^---/.exec(l)) {
            isYaml = false;
          } else {
            yaml = yaml + "\n" + l;
          }
        } else {
          if (/^---/.exec(l)) {
            isYaml = true;
            yaml = yaml + "\n" + l;
          } else {
            content = content + "\n" + l;
          }
        }
      }
      data = {};
      post = y.safeLoad(yaml);
      post.formattedDate = moment(post.date).format('dddd, MMMM Do YYYY');
      post.smallDate = moment(post.date).format('M/D');
      post.smallDescription = _(post.description).prune(70, '..');
      post.dirName = (post.category + "/") + moment(post.date).format('YYYY/MM/DD');
      post.fileName = _.slugify(post.title);
      data.post = post;
      data.mdContent = content;
      return data;
    };
    iface = {
      parse: parse
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
